Add tests for Quoting
thunderbird-conversations/thunderbird-conversations pull request #1560
Opened 2020-11-18 02:49 UTC by siefkenj

Add minimal tests for `Quoting` found in `quoting.js`. I don't have a good sample of different emails to pull from, so the tests consist of one real email and several made up ones. More should be added if someone has sample emails.

These APIs are called in exactly one place in `messageIFrame.jsx`. All methods could be consolidated to a single method `wrapBlockquotes` or something like that and then called once instead of being called in a sequence in `messageIFrame.jsx`.

All internal-use-only methods of `Quoting` have been prefixed with `_`. I think there are better ways to handle the quoting code. Right now it passes around a DOM and mutates it, which is no good if data needs to be passed between a webextension and the Thunderbird API. It would be nice if this turned into a string-based API, though I don't know the performance implications.

Also, I'm not sure how to test the `outlook` quoting method. It seems to rely on `getComputedStyle` which is only available for DOM nodes that are actually inserted into a real page. I don't have any samples of these types of messages, so I cannot analyze to find another way to do it.

2020-11-18 04:50 UTC, siefkenj commented
Upgraded Travis to `node-14` so that `?.` syntax would be recognized.

2020-11-23 09:50 UTC, Standard8 commented
Just to note I've seen this, I hope to get to it in the next day or so.

2020-11-24 17:07 UTC, Standard8 commented on addon/tests/quoting.test.js
> +const prettier = require("prettier");
Nice idea.

2020-11-29 11:30 UTC, Standard8 requested changes
Sorry, I keep forgetting to actually finish this review off.

I think this is really good to have some tests - thank you. There's one comment inline to potentially address.

Re string manipulation vs DOM, I think I'd be concerned that we'd end up writing or including our own specialist parser, when the DOM would do it for us. Obviously there's expense in using the DOM as well. So I'm not sure there's an easy "best" solution either way, which makes me tempted to keep it as it is for now.

2020-11-30 02:01 UTC, siefkenj commented on addon/tests/quoting.test.js
> +            <div style="font-family: Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0)">
I can remove them. I left them in because this was from an actual email (the other examples were hand-crafted).

2020-11-30 02:08 UTC, siefkenj commented
Thanks for the review :-).

As for string manipulation, I wasn't suggesting writing a DOM parser. I think `new DOMParser()` will work just fine for that. I was suggesting changing the interface to a string-based interface (it might parse to a DOM behind the scenes).

This would come with a slight performance penalty of parsing once to escape quoted blocks, and then TB parsing again when actually displaying the message. But, I don't think it will be too bad. If 100 messages are "open" at once, there will be bad performance either way (and probably the display code needs to be changed to only show messages that are scrolled into view anyways).

2020-11-30 02:12 UTC, siefkenj commented
Another question: What do you think about removing `convertOutlookQuotingToBlockquote` entirely until we have a sample email to test it on? The method requires not only a DOM, but a DOM attached to a rendered tree in order to use `getComputedStyle`. This makes it very hard to test and also very hard to decouple from display code, and if we had an actual example of such a message, there'd surely be another way to find the quote text.

2020-12-07 03:46 UTC, siefkenj commented
@Standard8 Any update on this?

2020-12-12 13:05 UTC, Standard8 commented
@siefkenj Sorry, I took a little time off from Conversations for a couple of weeks due to other priorities.

Re parsing, I think it would be an interesting idea to try out. Maybe there's an basic/rough outline or experiment could be done so it'd be easier to get an understanding of what it looks like.

For the outlook code, how about we try disabling it and pushing out an update, and seeing if it affects people? Worst case, we can always put it back in again.

2020-12-12 13:06 UTC, Standard8 approved these changes

2020-12-12 13:07 UTC, Standard8 commented
By the way, I've also enabled the new discussions feature now, so we can possibly move some of those discussions to there.

2020-12-12 13:07 UTC, merged