Add browser-accessible Dev-Frame
thunderbird-conversations/thunderbird-conversations pull request #1584
Opened 2021-01-03 03:49 UTC by siefkenj

Adds `dev-frame.html`, which is built when `dev` is built. In the dev frame you can test and rapid-develop Conversations components.

This PR s based on #1583. It is largely a proof-of-concept, but with files being watched and automatically recompiled, it makes development a lot faster! Also, there are clear errors when accessing Thunderbird-only APIs, so it should be easier to identify and split components, which should help in testing.

`MessageIFrame` seems to be deeply integrated with Thunderbird at the moment, so I inserted an `ErrorBoundary` component and just let it error for the time being.

2021-01-03 04:24 UTC, siefkenj commented
For some reason, this PR is causing the `browser` object to use the fallback version even though a real version should be available. Any idea why?

2021-01-30 13:54 UTC, siefkenj commented
@Standard8 Any ideas when you might be able to review this?

2021-01-31 12:01 UTC, Standard8 requested changes
This looks good to me, I do wonder if we should do this from the message list/conversation level, but it is a good start anyway.

I also wondered if we could do something like a console tracker for `browser.*` calls and have those output, for example you could click the reply button and check the call and its arguments.

We could do that later though, this is a good start in itself.

2021-01-31 12:02 UTC, Standard8 commented
And sorry for not responding earlier. I did think I had put some comments on it but obviously I hadn't got all the way through.

2021-01-31 16:23 UTC, siefkenj commented on addon/content/modules/message.js
> -
If something is imported as a module, doesn't it automatically get a `"use strict"`? In any case, I'll add it back.

2021-01-31 16:25 UTC, siefkenj commented
> I also wondered if we could do something like a console tracker for `browser.*` calls and have those output, for example you could click the reply button and check the call and its arguments.

You're thinking of this only when running in the browser, or in general whenever debug messages are enabled?

2021-01-31 18:07 UTC, Standard8 commented on addon/content/modules/message.js
> -
Not for the legacy modules that Firefox uses - these aren't es6 modules (yet).

2021-01-31 18:09 UTC, Standard8 commented
> > I also wondered if we could do something like a console tracker for `browser.*` calls and have those output, for example you could click the reply button and check the call and its arguments.
> 
> You're thinking of this only when running in the browser, or in general whenever debug messages are enabled?

I was thinking of only when running in the browser - maybe a separate text box or something.

2021-01-31 18:09 UTC, Standard8 approved these changes

2021-01-31 18:18 UTC, merged