Use CSS for the contact details popup
thunderbird-conversations/thunderbird-conversations pull request #1596
Opened 2021-02-06 04:45 UTC by siefkenj

Removes the complicated logic in the `Fade` component and instead uses CSS transitions to fade the contact details in and out (fade seems to have been broken for a while anyways...).

This PR also replaces the `_getSeparator` logic with `Intl.ListFormat`. I can't quite tell, but `header.commaSeparator` and `header.andSeparator` might be able to be removed after this is merged.

There is still one problem with long lists of contacts. For some reason, even though they're properly hidden if they overflow the Conversations window ends up with massive horizontal scrollbars. I'll have to look into this...

I also attempted to clean up some of the `ContactDetails` object. It's still confusing...can you lay out a standard of what it's supposed to look like given what properties? If I know when it's supposed to display what, I can write some tests.

2021-02-06 21:01 UTC, siefkenj commented
I believe I fixed the issue with the overflowing popups. Everything should work now :-)

2021-02-21 10:24 UTC, Standard8 requested changes
Did you use an old branch to base this on? The split options to show extra buttons at the bottom of the contacts popup seem to have come back. I got rid of that split a while ago, as I didn't think it was worth it.

The other thing I'm not quite sure about is when it gets shown. With this version of the patch if I move my mouse vertically across the contact, then the pop-up will start showing straight away.

I tried experimenting with a 400ms delay (roughly around the time of the current delay iirc), and it was better, though I was still finding that if you moved the mouse down and stopped before you get past the contact, then the contact detail was still prone to being displayed.

I'm not quite sure yet exactly how bad that is overall. Might need some more testing time.

Also I noticed that the "createFilter" text wasn't being replaced on the button.

2021-02-21 13:54 UTC, siefkenj commented
Yes, I did use an old version...(I was finishing up the work I started a year ago...). I'll update stuff to be in line with the new version and add a delay.

2021-02-21 15:05 UTC, siefkenj commented
Okay, hopefully things are good now!

2021-03-06 10:41 UTC, Standard8 requested changes
I've been trying this over the last week and not noticed any issues, so lets get this landed.

Just a minor couple of things to fix.

2021-03-06 10:41 UTC, Standard8 commented on addon/content/messageHeader.jsx
> +              //top: spanRef.current?.offsetTop + spanRef.current?.offsetHeight,
Can we drop these lines now?

2021-03-06 10:41 UTC, Standard8 commented on addon/content/messageHeader.jsx
> +export function ContactLabel({ contact, className }) {
nit: Line break before the export please

2021-03-06 15:05 UTC, siefkenj commented on addon/content/messageHeader.jsx
> +              //top: spanRef.current?.offsetTop + spanRef.current?.offsetHeight,
Oops!

2021-03-06 15:12 UTC, Standard8 approved these changes

2021-03-06 15:12 UTC, merged